call git add Makefile
call git add Makefile.Debug
call git add Makefile.Release
call git add c.bat
call git add d.bat
call git add FormsModel.h
call git add FormsModel.cpp
call git add main.cpp
call git add mainwindow.h
call git add mainwindow.cpp
call git add regen.bat
call git add regenvc.bat
call git add sfg.pro
call git add status.bat
call git add add_em.bat
call git add sfg_plugin_import.cpp
