call git add controllers/api/forms.js
call git add controllers/index.js
call git add models/form.js
call git add n.bat
call git add ng/forms-detail.ctrl.js
call git add ng/forms.ctrl.js
call git add ng/shared-utils.svc.js
call git add templates/forms-detail.html
call git add templates/forms.html
call git add test/FormDemo.js
call git add protractor.conf.js

call git add bower.json
call git add package.json
call git add server.js
call git add status.txt
call git add templates/forms.html
call git add test/e2e/doing_a_search.spec.js
call git add .jshintignore
call git add .jshintrc
call git add add_em.bat
call git add karma.conf.js
call git add protractor.conf.js
call git add run-blanket.bat
call git add run-istanbul.bat
call git add run-jshint.bat
call git add run-jshint.html
call git add run-mocha.bat
call git add run-protractor.bat
call git add test/mocha.opts
call git add test/server/controllers/api/forms-exists.spec.js
call git add test/server/controllers/api/forms.spec.js
call git add test/server/controllers/api/utils.spec.js
call git add test/server/support/coverage.js
call git add test/server/support/api.js
