#!/bin/bash
set -x
git add EdgarForm.h
git add EdgarForm.cpp
git add Forms.h
git add Forms.cpp
git add FormsMeanCommon.h
git add FormsMeanCommon.cpp
git add FormsMeanUtils.h
git add FormsMeanUtils.cpp
git add forms_mean_daemon.cpp
git add ftpget.cpp
git add mongoc.cpp

git add .gitignore
git add add_em.bat
git add add_em
git add c.bat
git add clean.bat
git add d.bat
git add d
git add m
git add v
git add v.bat
git add forms_mean_daemon.mak
git add mongoc.mak
git add Makefile

git add reference.txt
git add gotchas.txt 
git add nextel.txt 

git add status.bat
git add status.sh

git add build/forms_mean_daemon.ini

git add ../edgar/daily-index/master.20141031.idx
git add ../edgar/daily-index/master.20141031.sample.idx
git add ../edgar/data/1000180/0001242648-14-000081.txt

git add test/example-client.cpp
git add test/Makefile
git add test/build/README.TXT
git add test/c.bat
git add test/clean.bat
git add test/d.bat
git add test/d
git add test/m
git add test/example-client.mak

git add cpp_lib/tests/stooge.h
git add cpp_lib/MongoDbClient.h
git add cpp_lib/MongoDbClient.cpp
git add cpp_lib/tlogger.h
git add cpp_lib/utils.h
git add cpp_lib/utils.cpp

git add ../db.js
git add ../db/forms_insert.js
git add ../db/forms_setup.js
git add ../db/forms_view.js
git add ../db/mongoit.bat
git add ../db/setup.js
git add ../db/show.bat
git add ../db/show.js
git add ../get.bat
git add ../get.js
git add ../install.bat
git add ../lib/jutils.js
git add ../models/forms_index.js
git add ../package.json
git add ../status.bat
set +x
