#!/bin/bash
set -x
#gvim forms_mean_daemon.cpp Forms.h Forms.cpp FormsMeanUtils.h FormsMeanUtils.cpp FormsMeanCommon.h FormsMeanCommon.cpp cpp_lib/MongoDbClient.h cpp_lib/MongoDbClient.cpp test/example-client.cpp mongoc.cpp &
gvim sec_forms_daemon.cpp Forms.h Forms.cpp BsonFormParseTraverser.h BsonFormParseTraverser.cpp EdgarForm.h EdgarForm.cpp FormsMeanUtils.h FormsMeanUtils.cpp FormsMeanCommon.h FormsMeanCommon.cpp cpp_lib/MongoDbClient.h cpp_lib/MongoDbClient.cpp test/example-client.cpp mongoc.cpp &
set +x
